-- Why are you here?
-- Do not edit this file unless you know what you're doing!
-- Registers all configured happiness factors

local HM = {}

function HM.register(ech, config, Log)
-- Setup happiness factors
local function regHapFact(id, name, desc, boostPercent, boostDuration, decayRate, icon)
    ech:registerAsset({
        DataType = "HAPPINESS_FACTOR",
        Id = id,
        Name = name or (id .. "_NAME"),
        Description = desc or (id .. "_DESC"),
        IsSolvable = false,
        IsCumulative = true,
        Value = boostPercent,
        TimeBeforeDecayingSeconds = boostDuration,
        DecayingRatePerMinute = decayRate,
        --IsDecaying = true,                      --default
        --RemovedOnDecayed = true,                --default
        Icon = icon or "ICON_RESOURCE_MEAL",
    })
end

-- Register happiness factors
for _, hf in ipairs(config.HappinessFactors) do
    regHapFact(hf.id, hf.name, hf.desc, hf.boostPercent, hf.boostDuration, hf.decayRate, hf.icon)
    Log.logVerbose(ech, config, string.format("[Feast & Fortune] Registered Happiness Factor: %s", hf.id))
end
end

return HM
