-- Why are you here?
-- Do not edit this file unless you know what you're doing!
-- Centralized logging Utility by @Echelon - free to use in your mod

local LH = {}

function LH.logBase(ech, config, message, level)
    if config.EnableLogging and config.LogLevel >= level then
        ech:log(message)
    end
end

function LH.logCritical(ech, config, message) LH.logBase(ech, config, message, 1) end -- Always important
function LH.logInfo(ech, config, message)     LH.logBase(ech, config, message, 2) end -- Normal info
function LH.logVerbose(ech, config, message)  LH.logBase(ech, config, message, 3) end -- Debug/detail
function LH.logAlways(ech, _, message)        ech:log(message) end					  -- Forces output

return LH
