-- Why are you here?
-- Do not edit this file unless you know what you're doing!
-- Registers all configured meal quality tiers

local MR = {}

function MR.register(ech, config, Log)
-- Register tiered meal resources
local function registerTieredMeals(id, nameTag, icon)
    ech:registerAsset({
        DataType = "RESOURCE",
        Id = id,
        ResourceName = nameTag,
        OrderId = 200,
        Icon = icon or "ICON_RESOURCE_MEAL",
        ResourceTypeList = {"MEAL"},
        ResourceLayoutType = "BAGS",
        IsTradable = false,
        DisplayInToolbar = true,
        ResourceVisualPrefabList = {"PREFAB_RESOURCE_VISUAL_CRATE"},
        IndividualResourceVisualPrefabList = {"PREFAB_RESOURCE_VISUAL_CRATE"},
    })
end

-- Register all meal quality tiers
for _, tier in ipairs(config.mealQuality) do
    registerTieredMeals(tier.id, tier.name, tier.icon)
    Log.logVerbose(ech, config, string.format("[Feast & Fortune] Registered Meal Quality: %s", tier.id))
end
end

return MR
