-- Why are you here?
-- Do not edit this file unless you know what you're doing!
-- Loads recipes from user or default and addon DLC Recipe Books

local RL = {}

function RL.loadRecipes(ech, config, Log)
-- Counters
    local recipes = {}
    local recipeCount = 0
    local dlcRecipeCount = 0
-- Recipe Book Loader: Load either House-Recipes.lua or Your-Recipes.lua based on config
local recipes

if config.UserRecipeBook then
    local success, userRecipes = pcall(function()
        return ech:dofile("Recipe-Book/Your-Recipes.lua")
    end)

    if success and type(userRecipes) == "table" then
        recipes = userRecipes
        Log.logInfo(ech, config, "[Feast & Fortune] ✅ Loaded Recipe Book: Your-Recipes.lua")
    else
        Log.logInfo(ech, config, "[Feast & Fortune] ⚠️ Error in Recipe Book: Your-Recipes.lua – falling back to House Recipe Book: House-Recipes")
        recipes = ech:dofile("Recipe-Book/House-Recipes.lua")
    end
else
    recipes = ech:dofile("Recipe-Book/House-Recipes.lua")
    Log.logInfo(ech, config, "[Feast & Fortune] ✅ Using Default Recipe Book: House-Recipes")
end

-- DLC Loader
if config.SoupStewsBook then
    local success, SoupStewsBook = pcall(function()
        return ech:dofile("Recipe-Book/DLC/Soups-Stews.lua")
    end)

    if success and type(SoupStewsBook) == "table" then
		Log.logInfo(ech, config, string.format("[Feast & Fortune] Found %d DLC recipes", #SoupStewsBook))
            -- Add a flag to identify DLC recipes
        for _, r in ipairs(SoupStewsBook) do
            r.isDLC = true
            table.insert(recipes, r)
            dlcRecipeCount = dlcRecipeCount + 1
            -- Log each DLC recipe as it's added to the main list
            local nameKey = r.Name or ("Order #" .. (r.Order or "unknown"))
            Log.logVerbose(ech, config, string.format("[Feast & Fortune] Added DLC Recipe: %s", nameKey))
        end
         Log.logInfo(ech, config, string.format("[Feast & Fortune] ✅ Added %d Soups & Stews DLC recipes", dlcRecipeCount))
    else
        Log.logInfo(ech, config, "[Feast & Fortune] ⚠️ Failed to load Soups & Stews DLC")
    end
end
-- Log Recipe Books before processing
		return {
		recipes = recipes,
		recipeCount = recipeCount,
		dlcRecipeCount = dlcRecipeCount
	}
end

return RL
